"""Template renderers: plugins a DOCX template opts into.

Drop a module in this package with a Renderer subclass decorated by @register: it is discovered at
import time. DocumentService and ExportService call the hooks below; each one runs every registered
renderer that implements it, in `order`:

  extraction_requests  ExportService, before the extraction LLM call   (placeholder family)
  before_substitution  start of placeholder substitution               (placeholder family)
  after_substitution   end of placeholder substitution                 (placeholder family)
  prepare_output       {{output}} Markdown, before conversion to Word  (output family)
  format_output        Word elements inserted for {{output}}           (output family)

docs/TEMPLATE_RENDERERS.md is generated by render_docs().
"""
import importlib
import pkgutil
from typing import Any, Dict, List, Tuple

from .base import (LISTS_KEY, OUTPUT, PLACEHOLDER, REGISTRY, RenderContext, Renderer,
                   implemented_hooks, template_properties)

for _module in pkgutil.iter_modules(__path__):
    if _module.name != "base":
        importlib.import_module(f"{__name__}.{_module.name}")


def _running(hook: str):
    return [r for r in REGISTRY if hook in implemented_hooks(type(r))]


def extraction_requests(placeholders: List[str], parse, current_metadata: Dict[str, Any],
                        force: bool = False) -> Tuple[set, List[str]]:
    handled, requests = set(), []
    for r in _running("extraction_requests"):
        names, reqs = r.extraction_requests(placeholders, parse, current_metadata, force)
        handled |= names
        requests += reqs
    return handled, requests


def before_substitution(doc, placeholders: Dict[str, Any], set_run_text, rescue) -> None:
    ctx = RenderContext(placeholders, template_properties(doc), set_run_text, rescue)
    for r in _running("before_substitution"):
        r.before_substitution(doc, ctx)


def after_substitution(doc, placeholders: Dict[str, Any]) -> None:
    ctx = RenderContext(placeholders, template_properties(doc))
    for r in _running("after_substitution"):
        r.after_substitution(doc, ctx)


def prepare_output(doc, markdown: str) -> str:
    ctx = RenderContext(props=template_properties(doc))
    for r in _running("prepare_output"):
        markdown = r.prepare_output(doc, markdown, ctx)
    return markdown


def format_output(doc, inserted_elements) -> None:
    ctx = RenderContext(props=template_properties(doc))
    for r in _running("format_output"):
        r.format_output(doc, inserted_elements, ctx)


def render_docs() -> str:
    """Markdown documentation built from the registered renderers."""
    out = ["# Template renderers", "",
           "Généré par `app.services.template_renderers.render_docs()`. Un renderer est un plugin "
           "(`app/services/template_renderers/<nom>.py`) qui s'active par un élément du template et impose, "
           "le cas échéant, un contrat au prompt du service et aux consignes des placeholders.", ""]
    titles = {OUTPUT: "Renderers de sortie (agissent sur `{{output}}`)",
              PLACEHOLDER: "Renderers de placeholders (agissent sur les valeurs extraites)"}
    for family in (OUTPUT, PLACEHOLDER):
        out += [f"## {titles[family]}", ""]
        for r in (r for r in REGISTRY if r.family == family):
            doc = (type(r).__doc__ or "").strip().split("\n")[0]
            s = r.spec
            out += [f"### {r.name}", "", doc, "",
                    f"- **Déclencheur dans le template** : {s.trigger}",
                    f"- **Prompt du service** : {s.service_prompt}",
                    f"- **Consignes des placeholders** : {s.placeholder_prompt}",
                    f"- **Exemple** : `{s.example}`",
                    f"- **Étapes** : {', '.join(sorted(implemented_hooks(type(r))))}", ""]
    out += ["## Ajouter un renderer", "",
            "Créer `app/services/template_renderers/<nom>.py` avec une classe dérivée de `Renderer`, décorée par "
            "`@register`, qui définit `name`, `family`, `spec` et les seules étapes de sa famille. Régénérer ce fichier.", ""]
    return "\n".join(out)
