// Job monitoring types based on API contract

export type JobStatus = 'queued' | 'started' | 'processing' | 'completed' | 'failed' | 'cancelled';

export type PassType = 'initial' | 'continuation' | 'reduce' | 'summary' | 'single_pass' | 'extraction' | 'categorization';

// Version extraction cache entry
export interface VersionExtraction {
  metadata: Record<string, any>;
  template_id?: string;
  extracted_at: string;
}

// Job result structure (consolidated from result JSONB column)
export interface JobResult {
  output: string;
  extracted_metadata?: Record<string, any>;
  categorization?: JobCategorization;
  version_extractions?: Record<string, VersionExtraction>;
}

export interface JobCategorization {
  matched_tags?: Array<{ name: string; confidence: number }>;
  suggested_tags?: Array<{ name: string; confidence: number }>;
  _categorization_error?: string;
  _categorization_warning?: string;
}

// Processing phases
export type ProcessingPhase = 'processing' | 'reducing' | 'extracting' | 'generating_document';

export interface JobProgress {
  current: number;
  total: number;
  percentage: number;

  // Enhanced progress fields
  phase?: ProcessingPhase;
  current_batch?: number;
  total_batches?: number;
  completed_turns?: number;
  total_turns?: number;
  estimated_seconds_remaining?: number | null;

  // Reduce-specific fields (only present when phase === 'reducing')
  reduce_level?: number;
  reduce_items?: number;
  reduce_batch?: string;
}

// Token metrics for a single processing pass
export interface JobPassMetrics {
  pass_number: number;           // 1-indexed pass number
  pass_type: PassType;
  started_at: string;            // ISO 8601 datetime
  completed_at: string | null;   // ISO 8601 datetime (null if in progress)
  duration_ms: number;           // Processing time for this pass

  // Token breakdown
  prompt_tokens: number;         // Tokens in the prompt
  completion_tokens: number;     // Tokens generated by the model
  total_tokens: number;          // prompt + completion

  // Content metrics
  input_chars: number;           // Characters sent to model
  output_chars: number;          // Characters received from model

  // Cost tracking (optional)
  estimated_cost: number | null; // USD estimate based on model pricing
}

// Aggregated token metrics for a job
export interface JobTokenMetrics {
  // Per-pass breakdown
  passes: JobPassMetrics[];

  // Cumulative totals
  total_prompt_tokens: number;
  total_completion_tokens: number;
  total_tokens: number;
  total_duration_ms: number;
  total_estimated_cost: number | null;

  // Averages
  avg_tokens_per_pass: number;
  avg_duration_per_pass_ms: number;
}

// Current pass metrics from WebSocket
export interface CurrentPassMetrics {
  pass_number: number;
  pass_type: string;
  prompt_tokens: number;
  completion_tokens: number;
  duration_ms: number;
}

// Cumulative metrics from WebSocket
export interface CumulativeMetrics {
  total_tokens: number;
  total_prompt_tokens: number;
  total_completion_tokens: number;
  total_duration_ms: number;
  total_estimated_cost: number | null;
}

export interface JobResponse {
  id: string; // UUID (matches Celery task_id)
  service_id: string; // UUID
  service_name: string;
  flavor_name: string;
  status: JobStatus;
  created_at: string; // ISO 8601
  started_at: string | null; // ISO 8601
  completed_at: string | null; // ISO 8601
  result: JobResult | null; // Job result (contains output, extracted_metadata, categorization)
  error: string | null; // Error message if failed
  progress: JobProgress | null;
  organization_id: string | null; // Free-form string (max 100 chars)

  // Fallback tracking fields (populated at job creation)
  fallback_applied?: boolean;
  original_flavor_id?: string | null;
  original_flavor_name?: string | null;
  fallback_reason?: string | null;
  input_tokens?: number | null;
  context_available?: number | null;

  // Token metrics
  token_metrics: JobTokenMetrics | null;

  // Output type from flavor configuration
  output_type: 'text' | 'markdown' | 'json';

  // Version history fields
  current_version: number;
  last_edited_at: string | null;

  // Metadata extraction capability
  has_extraction_prompt: boolean;

  // Processing mode from flavor
  processing_mode: 'single_pass' | 'iterative';
}

export interface JobUpdate {
  job_id: string;
  status: JobStatus;
  progress?: JobProgress;
  result?: any;
  error?: string;
  timestamp: string;

  // Live metrics from WebSocket
  current_pass_metrics?: CurrentPassMetrics | null;
  cumulative_metrics?: CumulativeMetrics | null;
}

export interface JobListFilters {
  service_id?: string;
  status?: JobStatus;
  organization_id?: string;
  page?: number;
  page_size?: number;
}

// Job version history types
export interface JobVersionSummary {
  version_number: number;
  created_at: string;
  created_by: string | null;
  content_length: number;
}

export interface JobVersionDetail {
  version_number: number;
  created_at: string;
  created_by: string | null;
  content: string;
}

export interface JobResultUpdate {
  content: string;
}

// Note: The primary ExecuteServiceResponse is in types/service.ts
// This simplified version is kept for backward compatibility
export interface ExecuteServiceResponse {
  job_id: string;
  message?: string;
  status?: 'queued';
  // Fallback fields are in the full type at types/service.ts
}

// ============================================
// Global Jobs WebSocket Types
// ============================================

// Message types for global WebSocket
export type JobsWebSocketMessageType = 'jobs_snapshot' | 'job_update';

// Snapshot of active job for list display
export interface ActiveJobSnapshot {
  job_id: string;
  status: JobStatus;
  progress: JobProgress | null;
  service_name?: string;
  flavor_name?: string;
  created_at?: string;
}

// Initial snapshot message
export interface JobsSnapshotMessage {
  type: 'jobs_snapshot';
  jobs: ActiveJobSnapshot[];
  timestamp: string;
}

// Individual job update message (for global WS)
export interface JobUpdateBroadcast {
  type: 'job_update';
  job_id: string;
  status: JobStatus;
  progress: JobProgress | null;
  result?: any;
  error?: string | null;
  timestamp: string;
}

// Union type for all message types
export type JobsWebSocketMessage = JobsSnapshotMessage | JobUpdateBroadcast;
